/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ecc;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Afik & Hayyu
 */
public class ECCgui extends javax.swing.JApplet {
        
    /**
     * Initializes the applet ECCgui
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECCgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECCgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECCgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECCgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppTitle = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaEllipticalGroup1 = new javax.swing.JTextArea();
        labelInputP1 = new javax.swing.JLabel();
        btnSaveKeys1 = new javax.swing.JButton();
        labelGenerateKunci1 = new javax.swing.JLabel();
        btnGenerateEllipticalGroup1 = new javax.swing.JButton();
        btnGeneratePublicKey1 = new javax.swing.JButton();
        labelBasePoint1 = new javax.swing.JLabel();
        fieldInputP1 = new javax.swing.JTextField();
        fieldInputBasePoint1 = new javax.swing.JTextField();
        labelPublicKey1 = new javax.swing.JLabel();
        fieldPrivateKey1 = new javax.swing.JTextField();
        labelPrivateKey1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelEncrypt1 = new javax.swing.JLabel();
        btnBrowsePesan1 = new javax.swing.JButton();
        labelFilePesan1 = new javax.swing.JLabel();
        labelEncryptKey1 = new javax.swing.JLabel();
        fieldInputEncryptKey1 = new javax.swing.JTextField();
        btnBrowseEncryptKey1 = new javax.swing.JButton();
        btnEncrypt1 = new javax.swing.JButton();
        labelBasePointEnc1 = new javax.swing.JLabel();
        fieldInputBaseEnc1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        areaCipherEnc1 = new javax.swing.JTextArea();
        labelEncTime1 = new javax.swing.JLabel();
        labelInfoWaktuEnc1 = new javax.swing.JLabel();
        labelFilesize2 = new javax.swing.JLabel();
        labelInfoFilesize1 = new javax.swing.JLabel();
        btnSaveCipher1 = new javax.swing.JButton();
        labelKEnc1 = new javax.swing.JLabel();
        fieldInputKEnc1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        labelDecrypt1 = new javax.swing.JLabel();
        btnBrowseCipher1 = new javax.swing.JButton();
        labelFileCipher1 = new javax.swing.JLabel();
        labelDecryptKey1 = new javax.swing.JLabel();
        fieldInputDecryptKey1 = new javax.swing.JTextField();
        btnBrowseDecryptKey1 = new javax.swing.JButton();
        btnDecrypt1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        areaPesanDec1 = new javax.swing.JTextArea();
        labelDecTime1 = new javax.swing.JLabel();
        labelFilesize3 = new javax.swing.JLabel();
        btnSavePesan1 = new javax.swing.JButton();
        labelTimeDec1 = new javax.swing.JLabel();
        labelFilesizeDec1 = new javax.swing.JLabel();
        labelKDec = new javax.swing.JLabel();
        fieldInputBaseDec = new javax.swing.JTextField();
        labelBasePointDec = new javax.swing.JLabel();
        fieldInputKDec = new javax.swing.JTextField();
        labelOutputPubKey = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AppTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        AppTitle.setText("ECC Implementation");

        areaEllipticalGroup1.setColumns(20);
        areaEllipticalGroup1.setRows(5);
        jScrollPane6.setViewportView(areaEllipticalGroup1);

        labelInputP1.setText("p");

        btnSaveKeys1.setText("Save Keys");
        btnSaveKeys1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveKeys1MouseClicked(evt);
            }
        });

        labelGenerateKunci1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelGenerateKunci1.setText("Generate Kunci");

        btnGenerateEllipticalGroup1.setText("Get Elliptical Group");
        btnGenerateEllipticalGroup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateEllipticalGroup1MouseClicked(evt);
            }
        });
        btnGenerateEllipticalGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateEllipticalGroup1ActionPerformed(evt);
            }
        });

        btnGeneratePublicKey1.setText("Generate Public Key");
        btnGeneratePublicKey1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGeneratePublicKey1MouseClicked(evt);
            }
        });

        labelBasePoint1.setText("Base Point");

        labelPublicKey1.setText("Public key :");

        labelPrivateKey1.setText("Private key");

        labelEncrypt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelEncrypt1.setText("Encrypt");

        btnBrowsePesan1.setText("Browse pesan");
        btnBrowsePesan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowsePesan1MouseClicked(evt);
            }
        });
        btnBrowsePesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePesan1ActionPerformed(evt);
            }
        });

        labelFilePesan1.setText("Tidak ada file yang dipilih...");

        labelEncryptKey1.setText("Encrypt key");

        btnBrowseEncryptKey1.setText("Browse");
        btnBrowseEncryptKey1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseEncryptKey1MouseClicked(evt);
            }
        });

        btnEncrypt1.setText("Encrypt!");
        btnEncrypt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncrypt1MouseClicked(evt);
            }
        });

        labelBasePointEnc1.setText("Base Point");

        areaCipherEnc1.setColumns(20);
        areaCipherEnc1.setRows(5);
        jScrollPane7.setViewportView(areaCipherEnc1);

        labelEncTime1.setText("Waktu :");

        labelFilesize2.setText("Filesize :");

        btnSaveCipher1.setText("Save Ciphertext");
        btnSaveCipher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveCipher1MouseClicked(evt);
            }
        });
        btnSaveCipher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCipher1ActionPerformed(evt);
            }
        });

        labelKEnc1.setText("k");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(labelBasePointEnc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldInputBaseEnc1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(labelEncryptKey1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldInputEncryptKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(labelKEnc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldInputKEnc1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowseEncryptKey1)))
                    .addComponent(labelEncrypt1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnBrowsePesan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFilePesan1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelEncTime1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelInfoWaktuEnc1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelFilesize2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelInfoFilesize1))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSaveCipher1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEncrypt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEncrypt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowsePesan1)
                    .addComponent(labelFilePesan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEncryptKey1)
                    .addComponent(fieldInputEncryptKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseEncryptKey1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBasePointEnc1)
                    .addComponent(fieldInputBaseEnc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKEnc1)
                    .addComponent(fieldInputKEnc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncrypt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEncTime1)
                    .addComponent(labelInfoWaktuEnc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilesize2)
                    .addComponent(labelInfoFilesize1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveCipher1)
                .addContainerGap())
        );

        labelDecrypt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDecrypt1.setText("Decrypt");

        btnBrowseCipher1.setText("Browse cipher");
        btnBrowseCipher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseCipher1MouseClicked(evt);
            }
        });
        btnBrowseCipher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseCipher1ActionPerformed(evt);
            }
        });

        labelFileCipher1.setText("Tidak ada file yang dipilih...");

        labelDecryptKey1.setText("Decrypt key");

        btnBrowseDecryptKey1.setText("Browse");
        btnBrowseDecryptKey1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseDecryptKey1MouseClicked(evt);
            }
        });

        btnDecrypt1.setText("Decrypt!");
        btnDecrypt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecrypt1MouseClicked(evt);
            }
        });

        areaPesanDec1.setColumns(20);
        areaPesanDec1.setRows(5);
        jScrollPane8.setViewportView(areaPesanDec1);

        labelDecTime1.setText("Waktu :");

        labelFilesize3.setText("Filesize :");

        btnSavePesan1.setText("Save Pesan");

        labelKDec.setText("k");

        labelBasePointDec.setText("Base Point");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelDecryptKey1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldInputDecryptKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnBrowseDecryptKey1))
                    .addComponent(labelDecrypt1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBrowseCipher1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFileCipher1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelDecTime1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTimeDec1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelFilesize3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFilesizeDec1))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSavePesan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDecrypt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelBasePointDec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldInputBaseDec)
                        .addGap(18, 18, 18)
                        .addComponent(labelKDec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldInputKDec, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDecrypt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowseCipher1)
                    .addComponent(labelFileCipher1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDecryptKey1)
                    .addComponent(fieldInputDecryptKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseDecryptKey1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBasePointDec)
                    .addComponent(fieldInputBaseDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKDec)
                    .addComponent(fieldInputKDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnDecrypt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDecTime1)
                    .addComponent(labelTimeDec1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilesize3)
                    .addComponent(labelFilesizeDec1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSavePesan1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(labelInputP1)
                                .addGap(18, 18, 18)
                                .addComponent(fieldInputP1))
                            .addComponent(labelGenerateKunci1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateEllipticalGroup1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(labelPublicKey1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelOutputPubKey))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(labelPrivateKey1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldPrivateKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(labelBasePoint1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldInputBasePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGeneratePublicKey1))
                                    .addComponent(btnSaveKeys1)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGenerateKunci1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputP1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldInputP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerateEllipticalGroup1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrivateKey1)
                            .addComponent(fieldPrivateKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBasePoint1)
                            .addComponent(fieldInputBasePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGeneratePublicKey1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPublicKey1)
                            .addComponent(btnSaveKeys1)
                            .addComponent(labelOutputPubKey))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jScrollPane5.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 512, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateEllipticalGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateEllipticalGroup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateEllipticalGroup1ActionPerformed

    private void btnBrowseCipher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseCipher1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseCipher1ActionPerformed

    private void btnBrowsePesan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowsePesan1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String sb = "";
        String fullPath = "";
        String tempPesan;
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
                    File selectedfile = fc.getSelectedFile();
                    sb += selectedfile.getName();
                    fullPath += selectedfile.getAbsolutePath();
                    this.labelFilePesan1.setText(sb);
                    this.filePath = fullPath;
                    double fileSize = selectedfile.length();
                    this.labelInfoFilesize1.setText(Double.toString(fileSize) + " byte");
            try {
                tempPesan = ecc.readFile(fullPath);
                ecc.setPesan(tempPesan);
                byte[] pesan = ecc.readFileToBytes(filePath);
                ecc.setPesanInByte(pesan);
                System.out.println (ecc.getPesan());
                for (int i=0; i<pesan.length; i++){
                    System.out.print(pesan[i] + " ");
                }
            } catch (IOException ex) {
                Logger.getLogger(ECCgui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowsePesan1MouseClicked

    private void btnGenerateEllipticalGroup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateEllipticalGroup1MouseClicked
        // TODO add your handling code here:
        long p;
        String ellipticGroup = "";
        p = (long)Integer.parseInt(fieldInputP1.getText());
        ecc.getCurve().setP(p);
        ecc.getCurve().setEllipticGrup();
        ArrayList<Point> p_temp = new ArrayList<>();
        p_temp = ecc.getCurve().ellipticGroup;
        for (int i = 0; i<p_temp.size();i++){
            ellipticGroup += "(" + p_temp.get(i).getX() + "," + p_temp.get(i).getY() + ") ";
        }
        this.areaEllipticalGroup1.setText(ellipticGroup);
    }//GEN-LAST:event_btnGenerateEllipticalGroup1MouseClicked

    private void btnGeneratePublicKey1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneratePublicKey1MouseClicked
        // TODO add your handling code here:
        long privateKey;
        String bp_temp, x_temp, y_temp;
        x_temp = "";
        y_temp = "";
        privateKey = (long)Integer.parseInt(this.fieldPrivateKey1.getText());
        bp_temp = this.fieldInputBasePoint1.getText();
        
        //asumsi input user selalu dalam format "(x,y)" dan basepoint selalu benar
        int it = 1;
        do{
            x_temp += bp_temp.charAt(it);
            it++;
        }while(bp_temp.charAt(it)!= ',');
        do{
            y_temp += bp_temp.charAt(it+1);
            it++;
        }while(bp_temp.charAt(it+1)!= ')');
        basePoint.setX((long)Integer.parseInt(x_temp));
        basePoint.setY((long)Integer.parseInt(y_temp));
        
        Point publicKey = ecc.getCurve().perkalian(basePoint, privateKey);
        this.labelOutputPubKey.setText("("+publicKey.getX()+","+publicKey.getY()+")");
    }//GEN-LAST:event_btnGeneratePublicKey1MouseClicked

    private void btnSaveKeys1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveKeys1MouseClicked
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        String nf_pub = "";
        String nf_pri = "";
        int retval = jf.showSaveDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION){
            File savedFile = jf.getSelectedFile();
            nf_pub += savedFile.getAbsolutePath();
            nf_pub += ".pub";
            nf_pri += savedFile.getAbsolutePath();
            nf_pri += ".pri";
            try{
                PrintWriter data_pub = new PrintWriter(nf_pub);
                data_pub.println(this.labelOutputPubKey.getText());
                data_pub.close();
                PrintWriter data_pri = new PrintWriter(nf_pri);
                data_pri.println(this.fieldPrivateKey1.getText());
                data_pri.close();
            } catch (java.io.IOException e){
                System.out.println("Error saving file.");
            }
            
        }
    }//GEN-LAST:event_btnSaveKeys1MouseClicked

    private void btnBrowseEncryptKey1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseEncryptKey1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String sb = "";
        String fullPath = "";
        String tempText;
        String x_temp = "";
        String y_temp = "";
        Point pk_temp = new Point();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
                    File selectedfile = fc.getSelectedFile();
                    sb += selectedfile.getName();
                    fullPath += selectedfile.getAbsolutePath();
            try {
                String bp_temp = ecc.readFile(fullPath);
                int it = 1;
                do{
                    x_temp += bp_temp.charAt(it);
                    it++;
                }while(bp_temp.charAt(it)!= ',');
                do{
                    y_temp += bp_temp.charAt(it+1);
                    it++;
                }while(bp_temp.charAt(it+1)!= ')');
                pk_temp.setX((long)Integer.parseInt(x_temp));
                pk_temp.setY((long)Integer.parseInt(y_temp));
                ecc.setEncKey(pk_temp);
                this.fieldInputEncryptKey1.setText(bp_temp);
            } catch (IOException ex) {
                Logger.getLogger(ECCgui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowseEncryptKey1MouseClicked

    private void btnEncrypt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncrypt1MouseClicked
        // TODO add your handling code here:
        long startTime = System.nanoTime();
        ecc.getCurve().setP((long)Integer.parseInt(this.fieldInputP1.getText()));
        ecc.getCurve().setEllipticGrup();
        ecc.setAuxParam((long)Integer.parseInt(this.fieldInputKEnc1.getText()));
        String bp_temp = this.fieldInputBaseEnc1.getText();
        String x_temp = "";
        String y_temp = "";
        Point base = new Point();
        int it = 1;
        do{
            x_temp += bp_temp.charAt(it);
            it++;
        }while(bp_temp.charAt(it)!= ',');
        do{
            y_temp += bp_temp.charAt(it+1);
            it++;
        }while(bp_temp.charAt(it+1)!= ')');
        base.setX((long)Integer.parseInt(x_temp));
        base.setY((long)Integer.parseInt(y_temp));
        ecc.setBasePoint(base);
        String enckey_temp = this.fieldInputEncryptKey1.getText();
        x_temp = "";
        y_temp = "";
        Point enckey = new Point();
        it = 1;
        do{
            x_temp += enckey_temp.charAt(it);
            it++;
        }while(enckey_temp.charAt(it)!= ',');
        do{
            y_temp += enckey_temp.charAt(it+1);
            it++;
        }while(enckey_temp.charAt(it+1)!= ')');
        enckey.setX((long)Integer.parseInt(x_temp));
        enckey.setY((long)Integer.parseInt(y_temp));
        ecc.setEncKey(enckey);
        ecc.Encrypt();
        long endTime = System.nanoTime();
        long duration = (endTime - startTime)/1000000; 
        String cipherHexa = ecc.pointToHexa(ecc.getCipherYs());
        this.areaCipherEnc1.setText(cipherHexa);
        this.labelInfoWaktuEnc1.setText(duration + " miliseconds");
    }//GEN-LAST:event_btnEncrypt1MouseClicked

    private void btnBrowsePesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowsePesan1ActionPerformed

    private void btnSaveCipher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCipher1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveCipher1ActionPerformed

    private void btnSaveCipher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCipher1MouseClicked
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        String nf_enc = "";
        int retval = jf.showSaveDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION){
            File savedFile = jf.getSelectedFile();
            nf_enc += savedFile.getAbsolutePath();
            nf_enc += ".txt";
            try{
                PrintWriter data_pub = new PrintWriter(nf_enc);
                data_pub.println(this.labelOutputPubKey.getText());
                data_pub.close();
            } catch (java.io.IOException e){
                System.out.println("Error saving file.");
            }
            
        }
    }//GEN-LAST:event_btnSaveCipher1MouseClicked

    private void btnBrowseCipher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseCipher1MouseClicked
        JFileChooser fc = new JFileChooser();
        String sb = "";
        String fullPath = "";
        String tempCipher;
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
                    File selectedfile = fc.getSelectedFile();
                    sb += selectedfile.getName();
                    fullPath += selectedfile.getAbsolutePath();
                    this.labelFileCipher1.setText(sb);
                    this.filePath = fullPath;
                    double fileSize = selectedfile.length();
                    this.labelFilesizeDec1.setText(Double.toString(fileSize) + " byte");
            try {
                tempCipher = ecc.readFile(fullPath);
                ecc.setCipher(tempCipher);
                byte[] cib = ecc.hexaToByte(tempCipher);
                ecc.setCipherInByte(cib);
                System.out.println (ecc.getCipher());
                for (int i=0; i<cib.length; i++){
                    System.out.print(cib[i] + " ");
                }
            } catch (IOException ex) {
                Logger.getLogger(ECCgui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowseCipher1MouseClicked

    private void btnBrowseDecryptKey1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseDecryptKey1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String sb = "";
        String fullPath = "";
        String tempText;
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
                    File selectedfile = fc.getSelectedFile();
                    sb += selectedfile.getName();
                    fullPath += selectedfile.getAbsolutePath();
            try {
                String bp_temp = ecc.readFile(fullPath);
                System.out.println("key di ecc : " + ecc.getDecKey());
                ecc.setDecKey(Long.parseLong(bp_temp));
                this.fieldInputDecryptKey1.setText(bp_temp);
            } catch (IOException ex) {
                Logger.getLogger(ECCgui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            System.out.println("ajsbdjasbd");
        }
    }//GEN-LAST:event_btnBrowseDecryptKey1MouseClicked

    private void btnDecrypt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecrypt1MouseClicked
        ecc.getCurve().setP((long)Integer.parseInt(this.fieldInputP1.getText()));
        ecc.getCurve().setEllipticGrup();
        ecc.setAuxParam((long)Integer.parseInt(this.fieldInputKDec.getText()));
        String bp_temp = this.fieldInputBaseDec.getText();
        String x_temp = "";
        String y_temp = "";
        Point base = new Point();
        int it = 1;
        do{
            x_temp += bp_temp.charAt(it);
            it++;
        }while(bp_temp.charAt(it)!= ',');
        do{
            y_temp += bp_temp.charAt(it+1);
            it++;
        }while(bp_temp.charAt(it+1)!= ')');
        base.setX((long)Integer.parseInt(x_temp));
        base.setY((long)Integer.parseInt(y_temp));
        ecc.setBasePoint(base);
        String sdecKey = this.fieldInputDecryptKey1.getText();
        long decKey = (long) Integer.parseInt(sdecKey);
        ecc.setDecKey(decKey);
        ecc.setCipherInByte(ecc.hexaToByte(ecc.getCipher()));
        ecc.Decrypt();
        String pesan = ecc.getPesan();
        this.areaCipherEnc1.setText(pesan);
    }//GEN-LAST:event_btnDecrypt1MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppTitle;
    private javax.swing.JTextArea areaCipherEnc1;
    private javax.swing.JTextArea areaEllipticalGroup1;
    private javax.swing.JTextArea areaPesanDec1;
    private javax.swing.JButton btnBrowseCipher1;
    private javax.swing.JButton btnBrowseDecryptKey1;
    private javax.swing.JButton btnBrowseEncryptKey1;
    private javax.swing.JButton btnBrowsePesan1;
    private javax.swing.JButton btnDecrypt1;
    private javax.swing.JButton btnEncrypt1;
    private javax.swing.JButton btnGenerateEllipticalGroup1;
    private javax.swing.JButton btnGeneratePublicKey1;
    private javax.swing.JButton btnSaveCipher1;
    private javax.swing.JButton btnSaveKeys1;
    private javax.swing.JButton btnSavePesan1;
    private javax.swing.JTextField fieldInputBaseDec;
    private javax.swing.JTextField fieldInputBaseEnc1;
    private javax.swing.JTextField fieldInputBasePoint1;
    private javax.swing.JTextField fieldInputDecryptKey1;
    private javax.swing.JTextField fieldInputEncryptKey1;
    private javax.swing.JTextField fieldInputKDec;
    private javax.swing.JTextField fieldInputKEnc1;
    private javax.swing.JTextField fieldInputP1;
    private javax.swing.JTextField fieldPrivateKey1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelBasePoint1;
    private javax.swing.JLabel labelBasePointDec;
    private javax.swing.JLabel labelBasePointEnc1;
    private javax.swing.JLabel labelDecTime1;
    private javax.swing.JLabel labelDecrypt1;
    private javax.swing.JLabel labelDecryptKey1;
    private javax.swing.JLabel labelEncTime1;
    private javax.swing.JLabel labelEncrypt1;
    private javax.swing.JLabel labelEncryptKey1;
    private javax.swing.JLabel labelFileCipher1;
    private javax.swing.JLabel labelFilePesan1;
    private javax.swing.JLabel labelFilesize2;
    private javax.swing.JLabel labelFilesize3;
    private javax.swing.JLabel labelFilesizeDec1;
    private javax.swing.JLabel labelGenerateKunci1;
    private javax.swing.JLabel labelInfoFilesize1;
    private javax.swing.JLabel labelInfoWaktuEnc1;
    private javax.swing.JLabel labelInputP1;
    private javax.swing.JLabel labelKDec;
    private javax.swing.JLabel labelKEnc1;
    private javax.swing.JLabel labelOutputPubKey;
    private javax.swing.JLabel labelPrivateKey1;
    private javax.swing.JLabel labelPublicKey1;
    private javax.swing.JLabel labelTimeDec1;
    // End of variables declaration//GEN-END:variables
    //Atribut tambahan
    private ECC ecc = new ECC();
    private String filePath;
    private Point basePoint = new Point();

    
}
